name: Static Checkout â™»

on:
  push:
    paths:
      - '.github/**'

  pull_request:
    paths:
      - '.github/**'

permissions:
  actions: write
  contents: read
  security-events: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Delete ALL workflow runs in this repository
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.DELETE_ACTION_RUN_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0                # Default is 30 days; must be 0 to delete ALL runs
          keep_minimum_runs: 0          # Do not keep any runs
          delete_workflow_pattern: "${{ github.workflow }}"
          delete_workflow_by_state_pattern: "ALL"
          delete_run_by_conclusion_pattern: "ALL"
          dry_run: false


  static-checkout:
    runs-on: ubuntu-latest
    needs: [ cleanup ]
    steps:
      - name: Static Checkout
        uses: actions/checkout@v4

      - name: Ruff Lint
        uses: chartboost/ruff-action@v1

